# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data_error.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Data_error(object):
    def setupUi(self, Data_error):
        Data_error.setObjectName("Data_error")
        Data_error.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(Data_error)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(Data_error)
        self.label.setGeometry(QtCore.QRect(40, 20, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Data_error)
        self.label_2.setGeometry(QtCore.QRect(70, 80, 271, 61))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Data_error)
        self.label_3.setGeometry(QtCore.QRect(70, 130, 241, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Data_error)
        self.label_4.setGeometry(QtCore.QRect(70, 170, 201, 21))
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Data_error)
        self.buttonBox.accepted.connect(Data_error.accept) # type: ignore
        self.buttonBox.rejected.connect(Data_error.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Data_error)

    def retranslateUi(self, Data_error):
        _translate = QtCore.QCoreApplication.translate
        Data_error.setWindowTitle(_translate("Data_error", "Dialog"))
        self.label.setText(_translate("Data_error", "Upload Data"))
        self.label_2.setText(_translate("Data_error", "Your data was not able to be clean"))
        self.label_3.setText(_translate("Data_error", "An error has occured."))
        self.label_4.setText(_translate("Data_error", "Please go back and retry."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Data_error = QtWidgets.QDialog()
    ui = Ui_Data_error()
    ui.setupUi(Data_error)
    Data_error.show()
    sys.exit(app.exec_())
